name: CI/CD for react ToDo

on:
  push:
    branches:
      - master
jobs:
  # build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd todo
          npm install

      - name: Build Project
        run: |
            cd todo
            npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production file
          path: ./todo/build

  # Deploy Job 
  deploy:

    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: production file
          path: ./todo/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }}
          publish_dir: ./todo/build
